# Ticket_DA-001 - Customer Revenue Summary\n
\n
Write your analysis here.

In [157]:
import pandas as pd

In [158]:
#Task 1
customers = pd.read_csv("../../datasets/raw/customers.csv")
orders = pd.read_csv("../../datasets/raw/orders.csv")
order_items = pd.read_csv("../../datasets/raw/order_items.csv")

In [159]:
#Task 2
customers.head()

,customer_id,first_name,last_name,email,country,city,segment,signup_date,active
0,C0001,Sofía,García,sofia.garcia1@example.com,Colombia,Bogotá,Student,2022-06-02,False
1,C0002,Camila,Flores,camila.flores2@example.com,Costa Rica,Cartago,Student,2023-05-05,True
2,C0003,Gabriela,Ramírez,gabriela.ramirez3@example.com,Chile,Santiago,Standard,2024-10-25,True
3,C0004,Camila,García,camila.garcia4@example.com,Guatemala,Mixco,Standard,2024-04-12,True
4,C0005,Carlos,Hernández,carlos.hernandez5@example.com,Costa Rica,Alajuela,Standard,2022-11-04,True

In [160]:
#Task 2
orders.head()

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
1,O00002,C0087,ST004,2025-11-30,Online,Cash,Completed,NaN
2,O00003,C0015,ST005,2025-06-09,Retail,Cash,Completed,CMP003
3,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN
4,O00005,C0137,ST004,2025-11-24,Retail,Bank Transfer,Completed,NaN

In [161]:
#Task 2
order_items.head()

  order_item_id order_id product_id  quantity  unit_price  discount_pct
0      OI000001   O00001     PRD024       2.0        13.9             0
1      OI000002   O00001     PRD006       1.0        42.9             0
2      OI000003   O00001     PRD024       4.0        13.9             0
3      OI000004   O00001     PRD020       4.0        59.9             0
4      OI000005   O00001     PRD016       4.0        11.9             0

In [162]:
#Task 3
completed_orders = orders[orders['status'] == 'Completed'].copy()
completed_orders

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
1,O00002,C0087,ST004,2025-11-30,Online,Cash,Completed,NaN
2,O00003,C0015,ST005,2025-06-09,Retail,Cash,Completed,CMP003
3,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN
4,O00005,C0137,ST004,2025-11-24,Retail,Bank Transfer,Completed,NaN
...,...,...,...,...,...,...,...,...
895,O00896,C0068,ST007,2025-11-30,Online,PayPal,Completed,CMP005
897,O00898,C0083,ST004,2025-08-13,Online,Credit Card,Completed,NaN
898,O00899,C0090,ST005,2025-07-20,Online,Credit Card,Completed,NaN
899,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
900,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN

In [163]:
#Task 4
valid_items = order_items[order_items['unit_price'] != 0].copy()
valid_items

     order_item_id order_id product_id  quantity  unit_price  discount_pct
0         OI000001   O00001     PRD024       2.0        13.9             0
1         OI000002   O00001     PRD006       1.0        42.9             0
2         OI000003   O00001     PRD024       4.0        13.9             0
3         OI000004   O00001     PRD020       4.0        59.9             0
4         OI000005   O00001     PRD016       4.0        11.9             0
...            ...      ...        ...       ...         ...           ...
2756      OI002757   O00900     PRD024       4.0        13.9             0
2757      OI002758   O00900     PRD006       1.0        42.9            15
2758      OI002759   O00900     PRD010       2.0        27.9             0
2759      OI002760   O00900     PRD015       4.0        54.9            10
2760      OI000056   O00020     PRD007       3.0        17.9             0

[2760 rows x 6 columns]

In [164]:
#Task 5
valid_items['gross_amount'] = (valid_items['quantity'] * valid_items['unit_price'])
valid_items

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,gross_amount
0,OI000001,O00001,PRD024,2.0,13.9,0,27.8
1,OI000002,O00001,PRD006,1.0,42.9,0,42.9
2,OI000003,O00001,PRD024,4.0,13.9,0,55.6
3,OI000004,O00001,PRD020,4.0,59.9,0,239.6
4,OI000005,O00001,PRD016,4.0,11.9,0,47.6
...,...,...,...,...,...,...,...
2756,OI002757,O00900,PRD024,4.0,13.9,0,55.6
2757,OI002758,O00900,PRD006,1.0,42.9,15,42.9
2758,OI002759,O00900,PRD010,2.0,27.9,0,55.8
2759,OI002760,O00900,PRD015,4.0,54.9,10,219.6
2760,OI000056,O00020,PRD007,3.0,17.9,0,53.7

In [165]:
#Task 6
valid_items['net_amount'] = (valid_items['gross_amount'] * (1 - valid_items['discount_pct'] / 100))
valid_items

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,gross_amount,net_amount
0,OI000001,O00001,PRD024,2.0,13.9,0,27.8,27.800
1,OI000002,O00001,PRD006,1.0,42.9,0,42.9,42.900
2,OI000003,O00001,PRD024,4.0,13.9,0,55.6,55.600
3,OI000004,O00001,PRD020,4.0,59.9,0,239.6,239.600
4,OI000005,O00001,PRD016,4.0,11.9,0,47.6,47.600
...,...,...,...,...,...,...,...,...
2756,OI002757,O00900,PRD024,4.0,13.9,0,55.6,55.600
2757,OI002758,O00900,PRD006,1.0,42.9,15,42.9,36.465
2758,OI002759,O00900,PRD010,2.0,27.9,0,55.8,55.800
2759,OI002760,O00900,PRD015,4.0,54.9,10,219.6,197.640
2760,OI000056,O00020,PRD007,3.0,17.9,0,53.7,53.700

In [166]:
#Task 7

orders_by_customers = completed_orders.merge(customers, how='left', on='customer_id')
final_dataframe = orders_by_customers.merge(valid_items, how='left', on='order_id')
final_dataframe

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id,first_name,last_name,...,segment,signup_date,active,order_item_id,product_id,quantity,unit_price,discount_pct,gross_amount,net_amount
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Miguel,Flores,...,Standard,2024-02-20,True,OI000001,PRD024,2.0,13.9,0,27.8,27.80
1,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Miguel,Flores,...,Standard,2024-02-20,True,OI000002,PRD006,1.0,42.9,0,42.9,42.90
2,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Miguel,Flores,...,Standard,2024-02-20,True,OI000003,PRD024,4.0,13.9,0,55.6,55.60
3,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Miguel,Flores,...,Standard,2024-02-20,True,OI000004,PRD020,4.0,59.9,0,239.6,239.60
4,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Miguel,Flores,...,Standard,2024-02-20,True,OI000005,PRD016,4.0,11.9,0,47.6,47.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2416,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,Mateo,Pérez,...,Standard,2022-04-09,True,OI002759,PRD010,2.0,27.9,0,55.8,55.80
2417,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,Mateo,Pérez,...,Standard,2022-04-09,True,OI002760,PRD015,4.0,54.9,10,219.6,197.64
2418,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,Oscar,Rodríguez,...,Corporate,2024-09-26,True,OI000008,PRD008,3.0,49.9,0,149.7,149.70
2419,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,Oscar,Rodríguez,...,Corporate,2024-09-26,True,OI000009,PRD016,2.0,11.9,0,23.8,23.80
2420,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,Oscar,Rodríguez,...,Corporate,2024-09-26,True,OI000010,PRD023,2.0,29.9,0,59.8,59.80

In [167]:
#Task 8 - 9
grouped_customer = final_dataframe.groupby(['customer_id', 'first_name', 'last_name', 'country', 'segment']).agg(
    purchase_count=("order_id", "nunique"),
    total_quantity=("quantity", "sum"),
    total_revenue=("net_amount", "sum")
).reset_index()
grouped_customer

,customer_id,first_name,last_name,country,segment,purchase_count,total_quantity,total_revenue
0,C0002,Camila,Flores,Costa Rica,Student,6,32.0,1576.615
1,C0003,Gabriela,Ramírez,Chile,Standard,4,29.0,1328.320
2,C0004,Camila,García,Guatemala,Standard,7,41.0,1577.405
3,C0005,Carlos,Hernández,Costa Rica,Standard,11,95.0,3877.840
4,C0006,Sofía,Vargas,Chile,Premium,8,61.0,2103.880
...,...,...,...,...,...,...,...,...
121,C0145,Diego,Martínez,Colombia,Standard,4,28.0,1409.764
122,C0147,Diana,Torres,Panama,Premium,1,6.0,266.420
123,C0148,Adriana,Torres,Panama,Premium,2,11.0,548.700
124,C0149,Sofía,Gómez,Chile,Standard,8,77.0,2599.775
125,C0150,Lucía,Ramírez,Guatemala,Premium,5,52.0,2289.245

In [168]:
#Task 10
grouped_customer.sort_values(by='total_revenue', ascending=False)

,customer_id,first_name,last_name,country,segment,purchase_count,total_quantity,total_revenue
50,C0059,Luis,Castro,Chile,Corporate,11,116.0,4222.030
108,C0129,Javier,Martínez,Panama,Standard,10,95.0,4193.550
91,C0107,Carlos,Torres,Guatemala,Student,9,78.0,3892.665
3,C0005,Carlos,Hernández,Costa Rica,Standard,11,95.0,3877.840
62,C0073,Martín,Ramírez,Colombia,Premium,11,78.0,3811.755
...,...,...,...,...,...,...,...,...
7,C0009,Diana,Rojas,Mexico,Premium,2,17.0,446.300
69,C0080,Gabriela,Hernández,Mexico,Standard,2,10.0,446.000
100,C0120,Mateo,Vargas,Chile,Premium,4,19.0,399.630
88,C0104,Ana,Hernández,Costa Rica,Student,2,11.0,288.900
122,C0147,Diana,Torres,Panama,Premium,1,6.0,266.420

In [169]:
#Task 11
grouped_customer.to_csv('../../output/customer_revenue_summary.csv')