# Ticket_DA-002 - Product Sales Performance\n
\n
Write your analysis here.

In [3]:
import pandas as pd

In [4]:
#Task 1
products = pd.read_csv('../../datasets/raw/products.csv')
orders = pd.read_csv('../../datasets/raw/orders.csv')
order_items = pd.read_csv('../../datasets/raw/order_items.csv')

In [5]:
#Task 2
completed_orders = orders[orders['status'] == 'Completed'].copy()
completed_orders

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
1,O00002,C0087,ST004,2025-11-30,Online,Cash,Completed,NaN
2,O00003,C0015,ST005,2025-06-09,Retail,Cash,Completed,CMP003
3,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN
4,O00005,C0137,ST004,2025-11-24,Retail,Bank Transfer,Completed,NaN
...,...,...,...,...,...,...,...,...
895,O00896,C0068,ST007,2025-11-30,Online,PayPal,Completed,CMP005
897,O00898,C0083,ST004,2025-08-13,Online,Credit Card,Completed,NaN
898,O00899,C0090,ST005,2025-07-20,Online,Credit Card,Completed,NaN
899,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
900,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN

In [6]:
products

,product_id,product_name,category,subcategory,supplier_id,cost,list_price,active
0,PRD001,Runner Pro Shoes,Footwear,Running,SUP001,74.9,119.9,True
1,PRD002,TrailGrip Shoes,Footwear,Outdoor,SUP001,69.5,109.9,True
2,PRD003,Flex Training Shirt,Apparel,Training,SUP002,14.2,29.9,True
3,PRD004,DryFit Running Shirt,Apparel,Running,SUP002,16.4,34.9,True
4,PRD005,Performance Shorts,Apparel,Training,SUP004,13.8,32.5,True
5,PRD006,Compression Leggings,Apparel,Training,SUP004,18.9,42.9,True
6,PRD007,Hydro Bottle 750ml,Accessories,Hydration,SUP003,6.1,17.9,True
7,PRD008,Gym Backpack 25L,Accessories,Training,SUP003,22.3,49.9,True
8,PRD009,Training Gloves,Accessories,Training,SUP003,7.5,19.9,True
9,PRD010,Yoga Mat Basic,Equipment,Yoga,SUP005,11.6,27.9,True
10,PRD011,Yoga Mat Pro,Equipment,Yoga,SUP005,20.1,49.9,True
11,PRD012,Resistance Bands Set,Equipment,Training,SUP005,8.9,24.9,True
12,PRD013,Sports Cap,Accessories,Running,SUP004,5.2,16.9,True
13,PRD014,Running Socks Pack,Apparel,Running,SUP002,4.8,14.9,True
14,PRD015,Cycling Jersey,Apparel,Cycling,SUP002,21.4,54.9,True
15,PRD016,Bike Bottle Holder,Accessories,Cycling,SUP003,3.8,11.9,True
16,PRD017,Jump Rope Speed,Equipment,Training,SUP005,4.4,15.9,True
17,PRD018,Foam Roller,Equipment,Recovery,SUP005,9.7,26.9,True
18,PRD019,Recovery Massage Ball,Equipment,Recovery,SUP005,3.4,10.9,True
19,PRD020,Lightweight Hoodie,Apparel,Lifestyle,SUP004,24.0,59.9,True
20,PRD021,Everyday Sneakers,Footwear,Lifestyle,SUP001,44.8,89.9,True
21,PRD022,Soccer Training Ball,Equipment,Soccer,SUP003,12.5,31.9,True
22,PRD023,Goalkeeper Gloves,Accessories,Soccer,SUP003,10.8,29.9,True
23,PRD024,Ankle Support,Accessories,Recovery,SUP004,4.7,13.9,True
24,PRD025,Legacy Windbreaker,Apparel,Outdoor,SUP004,19.5,44.9,False

In [7]:
#Task 3
full_orders = completed_orders.merge(right=order_items, how='left', on='order_id').copy()
full_orders

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id,order_item_id,product_id,quantity,unit_price,discount_pct
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000001,PRD024,2.0,13.9,0
1,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000002,PRD006,1.0,42.9,0
2,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000003,PRD024,4.0,13.9,0
3,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000004,PRD020,4.0,59.9,0
4,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000005,PRD016,4.0,11.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,OI002759,PRD010,2.0,27.9,0
2418,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,OI002760,PRD015,4.0,54.9,10
2419,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000008,PRD008,3.0,49.9,0
2420,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000009,PRD016,2.0,11.9,0
2421,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000010,PRD023,2.0,29.9,0

In [8]:
#Task 4
orders_with_products = full_orders.merge(products, 'left', 'product_id')
orders_with_products

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id,order_item_id,product_id,quantity,unit_price,discount_pct,product_name,category,subcategory,supplier_id,cost,list_price,active
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000001,PRD024,2.0,13.9,0,Ankle Support,Accessories,Recovery,SUP004,4.7,13.9,True
1,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000002,PRD006,1.0,42.9,0,Compression Leggings,Apparel,Training,SUP004,18.9,42.9,True
2,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000003,PRD024,4.0,13.9,0,Ankle Support,Accessories,Recovery,SUP004,4.7,13.9,True
3,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000004,PRD020,4.0,59.9,0,Lightweight Hoodie,Apparel,Lifestyle,SUP004,24.0,59.9,True
4,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000005,PRD016,4.0,11.9,0,Bike Bottle Holder,Accessories,Cycling,SUP003,3.8,11.9,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,OI002759,PRD010,2.0,27.9,0,Yoga Mat Basic,Equipment,Yoga,SUP005,11.6,27.9,True
2418,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,OI002760,PRD015,4.0,54.9,10,Cycling Jersey,Apparel,Cycling,SUP002,21.4,54.9,True
2419,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000008,PRD008,3.0,49.9,0,Gym Backpack 25L,Accessories,Training,SUP003,22.3,49.9,True
2420,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000009,PRD016,2.0,11.9,0,Bike Bottle Holder,Accessories,Cycling,SUP003,3.8,11.9,True
2421,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000010,PRD023,2.0,29.9,0,Goalkeeper Gloves,Accessories,Soccer,SUP003,10.8,29.9,True

In [9]:
#Task 5
orders_with_products["net_amount"] = (orders_with_products["quantity"] * orders_with_products["unit_price"] * (1 - orders_with_products["discount_pct"] / 100))
orders_with_products

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id,order_item_id,product_id,...,unit_price,discount_pct,product_name,category,subcategory,supplier_id,cost,list_price,active,net_amount
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000001,PRD024,...,13.9,0,Ankle Support,Accessories,Recovery,SUP004,4.7,13.9,True,27.80
1,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000002,PRD006,...,42.9,0,Compression Leggings,Apparel,Training,SUP004,18.9,42.9,True,42.90
2,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000003,PRD024,...,13.9,0,Ankle Support,Accessories,Recovery,SUP004,4.7,13.9,True,55.60
3,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000004,PRD020,...,59.9,0,Lightweight Hoodie,Apparel,Lifestyle,SUP004,24.0,59.9,True,239.60
4,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,OI000005,PRD016,...,11.9,0,Bike Bottle Holder,Accessories,Cycling,SUP003,3.8,11.9,True,47.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,OI002759,PRD010,...,27.9,0,Yoga Mat Basic,Equipment,Yoga,SUP005,11.6,27.9,True,55.80
2418,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,OI002760,PRD015,...,54.9,10,Cycling Jersey,Apparel,Cycling,SUP002,21.4,54.9,True,197.64
2419,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000008,PRD008,...,49.9,0,Gym Backpack 25L,Accessories,Training,SUP003,22.3,49.9,True,149.70
2420,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000009,PRD016,...,11.9,0,Bike Bottle Holder,Accessories,Cycling,SUP003,3.8,11.9,True,23.80
2421,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN,OI000010,PRD023,...,29.9,0,Goalkeeper Gloves,Accessories,Soccer,SUP003,10.8,29.9,True,59.80

In [11]:
#Task 6 and 7
grouped_products = orders_with_products.groupby(['product_id', 'product_name', 'category', 'subcategory']).agg(units_sold = ('quantity', 'sum'), order_count = ('order_id','nunique'), total_revenue=('net_amount','sum')).reset_index()
grouped_products

,product_id,product_name,category,subcategory,units_sold,order_count,total_revenue
0,PRD001,Runner Pro Shoes,Footwear,Running,287.0,111,33669.119
1,PRD002,TrailGrip Shoes,Footwear,Outdoor,319.0,121,34331.661
2,PRD003,Flex Training Shirt,Apparel,Training,235.0,90,6814.210
3,PRD004,DryFit Running Shirt,Apparel,Running,262.0,106,8906.829
4,PRD005,Performance Shorts,Apparel,Training,215.0,82,6742.125
5,PRD006,Compression Leggings,Apparel,Training,252.0,95,10504.494
6,PRD007,Hydro Bottle 750ml,Accessories,Hydration,242.0,90,4193.970
7,PRD008,Gym Backpack 25L,Accessories,Training,235.0,95,11399.156
8,PRD009,Training Gloves,Accessories,Training,296.0,106,5719.260
9,PRD010,Yoga Mat Basic,Equipment,Yoga,229.0,81,6191.010
10,PRD011,Yoga Mat Pro,Equipment,Yoga,291.0,101,14155.133
11,PRD012,Resistance Bands Set,Equipment,Training,224.0,84,5391.597
12,PRD013,Sports Cap,Accessories,Running,258.0,100,4310.852
13,PRD014,Running Socks Pack,Apparel,Running,242.0,90,3509.993
14,PRD015,Cycling Jersey,Apparel,Cycling,200.0,83,10674.207
15,PRD016,Bike Bottle Holder,Accessories,Cycling,255.0,100,2928.233
16,PRD017,Jump Rope Speed,Equipment,Training,231.0,84,3570.663
17,PRD018,Foam Roller,Equipment,Recovery,268.0,95,6978.129
18,PRD019,Recovery Massage Ball,Equipment,Recovery,256.0,99,2727.943
19,PRD020,Lightweight Hoodie,Apparel,Lifestyle,236.0,88,13746.451
20,PRD021,Everyday Sneakers,Footwear,Lifestyle,281.0,112,24450.103
21,PRD022,Soccer Training Ball,Equipment,Soccer,243.0,84,7494.586
22,PRD023,Goalkeeper Gloves,Accessories,Soccer,242.0,95,7048.028
23,PRD024,Ankle Support,Accessories,Recovery,265.0,99,3627.622

In [14]:
#Task 8
grouped_products.sort_values(by='total_revenue', ascending=False)
grouped_products

,product_id,product_name,category,subcategory,units_sold,order_count,total_revenue
0,PRD001,Runner Pro Shoes,Footwear,Running,287.0,111,33669.119
1,PRD002,TrailGrip Shoes,Footwear,Outdoor,319.0,121,34331.661
2,PRD003,Flex Training Shirt,Apparel,Training,235.0,90,6814.210
3,PRD004,DryFit Running Shirt,Apparel,Running,262.0,106,8906.829
4,PRD005,Performance Shorts,Apparel,Training,215.0,82,6742.125
5,PRD006,Compression Leggings,Apparel,Training,252.0,95,10504.494
6,PRD007,Hydro Bottle 750ml,Accessories,Hydration,242.0,90,4193.970
7,PRD008,Gym Backpack 25L,Accessories,Training,235.0,95,11399.156
8,PRD009,Training Gloves,Accessories,Training,296.0,106,5719.260
9,PRD010,Yoga Mat Basic,Equipment,Yoga,229.0,81,6191.010
10,PRD011,Yoga Mat Pro,Equipment,Yoga,291.0,101,14155.133
11,PRD012,Resistance Bands Set,Equipment,Training,224.0,84,5391.597
12,PRD013,Sports Cap,Accessories,Running,258.0,100,4310.852
13,PRD014,Running Socks Pack,Apparel,Running,242.0,90,3509.993
14,PRD015,Cycling Jersey,Apparel,Cycling,200.0,83,10674.207
15,PRD016,Bike Bottle Holder,Accessories,Cycling,255.0,100,2928.233
16,PRD017,Jump Rope Speed,Equipment,Training,231.0,84,3570.663
17,PRD018,Foam Roller,Equipment,Recovery,268.0,95,6978.129
18,PRD019,Recovery Massage Ball,Equipment,Recovery,256.0,99,2727.943
19,PRD020,Lightweight Hoodie,Apparel,Lifestyle,236.0,88,13746.451
20,PRD021,Everyday Sneakers,Footwear,Lifestyle,281.0,112,24450.103
21,PRD022,Soccer Training Ball,Equipment,Soccer,243.0,84,7494.586
22,PRD023,Goalkeeper Gloves,Accessories,Soccer,242.0,95,7048.028
23,PRD024,Ankle Support,Accessories,Recovery,265.0,99,3627.622

In [15]:
#Task 9
grouped_products.to_csv('../../output/product_sales_performance.csv')