# Ticket_DA-003 - Store Daily Sales Report\n
\n
Write your analysis here.

In [87]:
import pandas as pd

In [88]:
#Task 1 Load stores, orders and order_items
stores = pd.read_csv('../../datasets/raw/stores.csv')
orders = pd.read_csv('../../datasets/raw/orders.csv')
order_items = pd.read_csv('../../datasets/raw/order_items.csv')

In [89]:
orders

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
1,O00002,C0087,ST004,2025-11-30,Online,Cash,Completed,NaN
2,O00003,C0015,ST005,2025-06-09,Retail,Cash,Completed,CMP003
3,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN
4,O00005,C0137,ST004,2025-11-24,Retail,Bank Transfer,Completed,NaN
...,...,...,...,...,...,...,...,...
896,O00897,C0023,ST004,2025-05-09,Retail,Cash,Returned,NaN
897,O00898,C0083,ST004,2025-08-13,Online,Credit Card,Completed,NaN
898,O00899,C0090,ST005,2025-07-20,Online,Credit Card,Completed,NaN
899,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
900,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN

In [90]:
order_items

     order_item_id order_id product_id  quantity  unit_price  discount_pct
0         OI000001   O00001     PRD024       2.0        13.9             0
1         OI000002   O00001     PRD006       1.0        42.9             0
2         OI000003   O00001     PRD024       4.0        13.9             0
3         OI000004   O00001     PRD020       4.0        59.9             0
4         OI000005   O00001     PRD016       4.0        11.9             0
...            ...      ...        ...       ...         ...           ...
2756      OI002757   O00900     PRD024       4.0        13.9             0
2757      OI002758   O00900     PRD006       1.0        42.9            15
2758      OI002759   O00900     PRD010       2.0        27.9             0
2759      OI002760   O00900     PRD015       4.0        54.9            10
2760      OI000056   O00020     PRD007       3.0        17.9             0

[2761 rows x 6 columns]

In [91]:
stores

,store_id,store_name,country,city,channel,opened_date,active
0,ST001,San Jose Central,Costa Rica,San José,Retail,2021-03-15,True
1,ST002,Escazu Outlet,Costa Rica,San José,Outlet,2022-08-01,True
2,ST003,Mexico City Reforma,Mexico,Mexico City,Retail,2020-10-12,True
3,ST004,Bogota North,Colombia,Bogotá,Retail,2021-11-05,True
4,ST005,Panama Online Hub,Panama,Panama City,Online,2023-01-20,True
5,ST006,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
6,ST007,Santiago Sport Center,Chile,Santiago,Retail,2022-02-18,True
7,ST008,Heredia Express,Costa Rica,Heredia,Retail,2024-04-01,False

In [92]:
#Task 2 Keep only completed orders
completed_orders = orders[orders['status'] == 'Completed'].copy()
completed_orders

,order_id,customer_id,store_id,order_date,channel,payment_method,status,campaign_id
0,O00001,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
1,O00002,C0087,ST004,2025-11-30,Online,Cash,Completed,NaN
2,O00003,C0015,ST005,2025-06-09,Retail,Cash,Completed,CMP003
3,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN
4,O00005,C0137,ST004,2025-11-24,Retail,Bank Transfer,Completed,NaN
...,...,...,...,...,...,...,...,...
895,O00896,C0068,ST007,2025-11-30,Online,PayPal,Completed,CMP005
897,O00898,C0083,ST004,2025-08-13,Online,Credit Card,Completed,NaN
898,O00899,C0090,ST005,2025-07-20,Online,Credit Card,Completed,NaN
899,O00900,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
900,O00004,C0039,ST001,2025-10-22,Online,PayPal,Completed,NaN

In [93]:
#Task 3 Create net_amount using quantity, unit_price and discount_pct
order_items['net_amount'] = (order_items['quantity'] * order_items['unit_price'] * (1 - order_items['discount_pct'] / 100))
order_items

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,net_amount
0,OI000001,O00001,PRD024,2.0,13.9,0,27.800
1,OI000002,O00001,PRD006,1.0,42.9,0,42.900
2,OI000003,O00001,PRD024,4.0,13.9,0,55.600
3,OI000004,O00001,PRD020,4.0,59.9,0,239.600
4,OI000005,O00001,PRD016,4.0,11.9,0,47.600
...,...,...,...,...,...,...,...
2756,OI002757,O00900,PRD024,4.0,13.9,0,55.600
2757,OI002758,O00900,PRD006,1.0,42.9,15,36.465
2758,OI002759,O00900,PRD010,2.0,27.9,0,55.800
2759,OI002760,O00900,PRD015,4.0,54.9,10,197.640
2760,OI000056,O00020,PRD007,3.0,17.9,0,53.700

In [94]:
#Task 4 Merge order_items with orders
orders_with_items = order_items.merge(completed_orders, how='left', on='order_id')
orders_with_items

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,net_amount,customer_id,store_id,order_date,channel,payment_method,status,campaign_id
0,OI000001,O00001,PRD024,2.0,13.9,0,27.800,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
1,OI000002,O00001,PRD006,1.0,42.9,0,42.900,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
2,OI000003,O00001,PRD024,4.0,13.9,0,55.600,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
3,OI000004,O00001,PRD020,4.0,59.9,0,239.600,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
4,OI000005,O00001,PRD016,4.0,11.9,0,47.600,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,OI002757,O00900,PRD024,4.0,13.9,0,55.600,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
2760,OI002758,O00900,PRD006,1.0,42.9,15,36.465,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
2761,OI002759,O00900,PRD010,2.0,27.9,0,55.800,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
2762,OI002760,O00900,PRD015,4.0,54.9,10,197.640,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN
2763,OI000056,O00020,PRD007,3.0,17.9,0,53.700,C0149,ST001,2025-06-25,Retail,Debit Card,Completed,NaN

In [95]:
#Task 5 Merge the result with stores
orders_with_items_stores = orders_with_items.merge(stores, how='left', on='store_id')
orders_with_items_stores

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,net_amount,customer_id,store_id,order_date,channel_x,payment_method,status,campaign_id,store_name,country,city,channel_y,opened_date,active
0,OI000001,O00001,PRD024,2.0,13.9,0,27.800,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
1,OI000002,O00001,PRD006,1.0,42.9,0,42.900,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
2,OI000003,O00001,PRD024,4.0,13.9,0,55.600,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
3,OI000004,O00001,PRD020,4.0,59.9,0,239.600,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
4,OI000005,O00001,PRD016,4.0,11.9,0,47.600,C0011,ST006,2025-02-22,Retail,Cash,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,OI002757,O00900,PRD024,4.0,13.9,0,55.600,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
2760,OI002758,O00900,PRD006,1.0,42.9,15,36.465,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
2761,OI002759,O00900,PRD010,2.0,27.9,0,55.800,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
2762,OI002760,O00900,PRD015,4.0,54.9,10,197.640,C0094,ST006,2025-10-19,Retail,Bank Transfer,Completed,NaN,Guatemala Mall,Guatemala,Guatemala City,Retail,2023-05-10,True
2763,OI000056,O00020,PRD007,3.0,17.9,0,53.700,C0149,ST001,2025-06-25,Retail,Debit Card,Completed,NaN,San Jose Central,Costa Rica,San José,Retail,2021-03-15,True

In [96]:
#Task 6 Group by order_date, store_id, store_name, country and city 
#Task 7 Calculate total_orders, total_items_sold and total_revenue
grouped_order_full_data = orders_with_items_stores.groupby(['order_date','store_id','store_name','country','city']).agg(total_orders = ('order_id', 'nunique'), total_items_sold = ('quantity', 'sum'), total_revenue = ('net_amount', 'sum'))
grouped_order_full_data

                                                                     total_orders  \
order_date store_id store_name            country    city
03/15/2025 ST002    Escazu Outlet         Costa Rica San José                   1
2025-01-01 ST006    Guatemala Mall        Guatemala  Guatemala City             1
2025-01-02 ST003    Mexico City Reforma   Mexico     Mexico City                1
2025-01-03 ST004    Bogota North          Colombia   Bogotá                     1
2025-01-04 ST002    Escazu Outlet         Costa Rica San José                   1
...                                                                           ...
2025-12-29 ST004    Bogota North          Colombia   Bogotá                     1
           ST007    Santiago Sport Center Chile      Santiago                   1
2025-12-30 ST002    Escazu Outlet         Costa Rica San José                   1
           ST003    Mexico City Reforma   Mexico     Mexico City                1
2025-12-31 ST003    Mexico City Reforma   Mexico     Mexico City                2

                                                                     total_items_sold  \
order_date store_id store_name            country    city
03/15/2025 ST002    Escazu Outlet         Costa Rica San José                     7.0
2025-01-01 ST006    Guatemala Mall        Guatemala  Guatemala City              15.0
2025-01-02 ST003    Mexico City Reforma   Mexico     Mexico City                  7.0
2025-01-03 ST004    Bogota North          Colombia   Bogotá                      12.0
2025-01-04 ST002    Escazu Outlet         Costa Rica San José                    15.0
...                                                                               ...
2025-12-29 ST004    Bogota North          Colombia   Bogotá                      13.0
           ST007    Santiago Sport Center Chile      Santiago                     9.0
2025-12-30 ST002    Escazu Outlet         Costa Rica San José                     6.0
           ST003    Mexico City Reforma   Mexico     Mexico City                  5.0
2025-12-31 ST003    Mexico City Reforma   Mexico     Mexico City                 23.0

                                                                     total_revenue
order_date store_id store_name            country    city
03/15/2025 ST002    Escazu Outlet         Costa Rica San José               520.30
2025-01-01 ST006    Guatemala Mall        Guatemala  Guatemala City         442.70
2025-01-02 ST003    Mexico City Reforma   Mexico     Mexico City            119.07
2025-01-03 ST004    Bogota North          Colombia   Bogotá                 494.02
2025-01-04 ST002    Escazu Outlet         Costa Rica San José               655.50
...                                                                            ...
2025-12-29 ST004    Bogota North          Colombia   Bogotá                 741.70
           ST007    Santiago Sport Center Chile      Santiago               301.10
2025-12-30 ST002    Escazu Outlet         Costa Rica San José               367.20
           ST003    Mexico City Reforma   Mexico     Mexico City            242.50
2025-12-31 ST003    Mexico City Reforma   Mexico     Mexico City            621.76

[666 rows x 3 columns]

In [97]:
#Task 8 Sort by order_date ascending and total_revenue descending
grouped_order_full_data = grouped_order_full_data.reset_index().sort_values(['order_date', 'total_revenue'], ascending=[True,False])
grouped_order_full_data

,order_date,store_id,store_name,country,city,total_orders,total_items_sold,total_revenue
0,03/15/2025,ST002,Escazu Outlet,Costa Rica,San José,1,7.0,520.30
1,2025-01-01,ST006,Guatemala Mall,Guatemala,Guatemala City,1,15.0,442.70
2,2025-01-02,ST003,Mexico City Reforma,Mexico,Mexico City,1,7.0,119.07
3,2025-01-03,ST004,Bogota North,Colombia,Bogotá,1,12.0,494.02
4,2025-01-04,ST002,Escazu Outlet,Costa Rica,San José,1,15.0,655.50
...,...,...,...,...,...,...,...,...
661,2025-12-29,ST004,Bogota North,Colombia,Bogotá,1,13.0,741.70
662,2025-12-29,ST007,Santiago Sport Center,Chile,Santiago,1,9.0,301.10
663,2025-12-30,ST002,Escazu Outlet,Costa Rica,San José,1,6.0,367.20
664,2025-12-30,ST003,Mexico City Reforma,Mexico,Mexico City,1,5.0,242.50
665,2025-12-31,ST003,Mexico City Reforma,Mexico,Mexico City,2,23.0,621.76

In [98]:
#Task 9 Export the result as output/store_daily_sales.csv
grouped_order_full_data.to_csv('../../output/store_daily_sales.csv', index=False)